### ISSUE TITLE
Please do not sleep

### ISSUE THREAD

**Issue by smorimoto** [treasure-data/td-ios-sdk#97] opened 2021-07-11 18:25 UTC
I use my DNS server to prevent all ads, trackers, and things like them, which unfortunately includes yours. The problem here is that the SDK's clearly unclever implementation causes a wait time of about 30 seconds for almost everything I do with the SMBC app, my bank. This should be fixed as soon as possible. And the problematic part seems to be here:

https://github.com/treasure-data/td-ios-sdk/blob/5ccf11ecfb40697d29d58a6aab504c01b1cccf19/TreasureData/TDClient.m#L129

Although I'm not an iOS expert, isn't sleeping in the block messing up the dispatch queue anyway? What is the reason to choose "coefficient" here? There are too many weird points.

**Comment by toru-takahashi** [comment] 2021-07-11 22:21
Hello,

thank you for your report.
This SDK handles error retries by exponential backoff[1] approach.
That's why it has coefficient.

Regarding to the `sleep` issue on your env, uploading logs with callback is recommenced to work in background or at app close that doesn't block a client app behavior. In addition, uploadEvent method supports both with callback and without callback. I'm not sure how they implement this SDK. But, i suppose it is a client's implementation issue rather than this SDK issue.

I'll forward this issue to the customer,  but I can't guaranteed that the issue will be fixed or not.

Thank you,

[1] https://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by smorimoto** [comment] 2021-07-12 04:05
OK - for instance, what happens if they couldn't resolve `tokyo.in.treasuredata.com`?

**Comment by smorimoto** [comment] 2021-07-12 04:15
Thank you for explaining the exponential backoff, but that wasn't my point anyway. Indeed I asked about the coefficient, but it doesn't mean I don't know about exponential backoff.

**Comment by toru-takahashi** [comment] 2021-07-12 08:30
Uploading data with a retry is expected behavior because a mobile network often is unstable.
First of all, our SDK can't choose a retry strategy like no-retry when it is a custom DNS or DNS name resolution fails.
In addition, we don't expect that DNS resolution to our service doesn't work forever because this SDK is intended to use an app that requires internet access. So, they will retry until the max retry count is exceeded.

On the other hand, I know there is a situation that people use own DNS or nextDNS or something like such a ad blocking service.
But, a policy for such a case depends on our customers. we can't change the current behavior.

In the end, I assume you are asking us why we use `sleepForTimeInterval:wait` for the exponential backoff. Because I guess the you observe the retry actually blocks the app behavior?
We expect the method is not called in a main thread. And the retry are not so long. We don't think it is a big issue.

But, we may have an alternative approach like using `dispatch_after` or some others.
Since the logic has been implemented since 2014, it is kept as-is for a long.
We will put an improvement to our backlog.

Thank you,

**Closed** 2022-09-11 12:42 UTC
